title: Tech and Geek
email: your-email@example.com
description: >-
  Technical blogs and guides on DevOps, SRE, infrastructure monitoring, and observability 
  using tools like Prometheus, Grafana, Alertmanager, Loki, and other enterprise tools.

url: "https://yourusername.github.io"  # Set this to your actual GitHub Pages URL
baseurl: ""  # Use "/repo-name" if it's not a user/org site

twitter_username: techndgeek
github_username: tech-and-geek

# Theme and appearance
remote_theme: mmistakes/minimal-mistakes@4.27.1
minimal_mistakes_skin: dark  # Options: default, dark, mint, air, etc.
search: true
timezone: Asia/Kolkata

# Logo and favicon (make sure these exist in /assets/images/)
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico

# Markdown processor
markdown: kramdown

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

# Output
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Directories to include
include:
  - _pages

# Navigation bar
navigation:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
  - title: "About"
    url: "/about/"
  - title: "Categories"
    url: "/categories/"
